"""
Executor de sessão Discord — Jules
Modo de uso: python bot.py <arquivo_de_tarefas.json>
Conecta, executa as tarefas, salva logs e desliga.
"""

import sys
import json
import os
import asyncio
import discord
from discord.ext import commands
from dotenv import load_dotenv
from core import SessionBot, channels, roles, members, inspect, permissions

load_dotenv()


ACTION_MAP = {
    "create_channel":              channels.create,
    "edit_channel":                channels.edit,
    "delete_channel":              channels.delete,
    "list_channels":               channels.list_channels,
    "create_role":                 roles.create,
    "edit_role":                   roles.edit,
    "delete_role":                 roles.delete,
    "list_roles":                  roles.list_roles,
    "timeout":                     members.timeout,
    "remove_timeout":              members.remove_timeout,
    "kick":                        members.kick,
    "ban":                         members.ban,
    "get_messages":                members.get_messages,
    "list_members":                members.list_members,
    "guild_info":                  inspect.guild_info,
    "channel_info":                inspect.channel_info,
    "role_info":                   inspect.role_info,
    "member_info":                 inspect.member_info,
    "audit_logs":                  inspect.audit_logs,
    "list_bans":                   inspect.list_bans,
    "guild_emojis":                inspect.guild_emojis,
    "channels_by_category":        inspect.channels_by_category,
    "search_messages":             inspect.search_messages,
    "role_hierarchy":              inspect.role_hierarchy,
    "member_activity":             inspect.member_activity,
    "role_summary":                inspect.role_summary,
    "set_channel_permissions":     permissions.set_channel_permissions,
    "sync_channel_permissions":    permissions.sync_channel_permissions,
    "get_channel_overwrites":      permissions.get_channel_overwrites,
    "send_message":                channels.send_message,
}


def carregar_tarefas(caminho):
    with open(caminho, "r", encoding="utf-8") as f:
        return json.load(f)


async def executar_sessao(token, guild_id, tarefas, caminho_resultado):
    session = SessionBot(guild_id)

    async def handler(s):
        s.log("INFO", f"Sessão iniciada no servidor: {s.guild.name}")
        for i, task in enumerate(tarefas, 1):
            action = task.get("action")
            params = task.get("params", {})
            nome = f"Tarefa {i}: {action}"
            print(f"\n--- {nome} ---")

            if action not in ACTION_MAP:
                s.log("ERRO", f"Ação desconhecida: {action}")
                continue

            try:
                await s.send_log_realtime("INFO", f"Iniciando tarefa {i}: `{action}`...")
                resultado = await ACTION_MAP[action](s, **params)
                if resultado is not None and action in ("list_channels", "list_roles", "list_members",
                                                        "get_messages", "guild_info", "channel_info",
                                                        "role_info", "member_info", "audit_logs",
                                                        "list_bans", "guild_emojis",
                                                        "channels_by_category", "search_messages",
                                                        "role_hierarchy", "member_activity",
                                                        "role_summary", "get_channel_overwrites"):
                    s.log("OK", f"Resultado: {json.dumps(resultado, ensure_ascii=False, default=str)[:500]}")

                # Fetch the last log generated by the action and send it
                if s.results:
                    last_log = s.results[-1]
                    if last_log["status"] != "INFO": # Don't resend the start info
                        await s.send_log_realtime(last_log["status"], last_log["details"])

            except Exception as e:
                s.log("FALHA", f"{action}: {e}")
                await s.send_log_realtime("FALHA", f"{action}: {e}")

        s.save_results(caminho_resultado)
        print(f"\nSessão concluída. {len([r for r in s.results if r['status'] == 'OK'])} OK, "
              f"{len([r for r in s.results if r['status'] == 'ERRO'])} erros, "
              f"{len([r for r in s.results if r['status'] == 'FALHA'])} falhas.")
        await s.close()

    session.on_ready = handler
    await session.run(token)


async def listar_servidores(token):
    """Conecta, lista servidores e desliga."""
    intents = discord.Intents.default()
    client = commands.Bot(command_prefix="!", intents=intents)

    @client.event
    async def on_ready():
        print(f"Bot: {client.user}\n")
        if not client.guilds:
            print("O bot não está em nenhum servidor.")
        else:
            for g in client.guilds:
                print(f"  [{g.id}] {g.name} — {g.member_count} membros")
        print(f"\nTotal: {len(client.guilds)} servidor(es)")
        await client.close()

    await client.start(token)


def main():
    token = os.getenv("DISCORD_TOKEN")
    if not token:
        print("Token não encontrado. Defina DISCORD_TOKEN como variável de ambiente.")
        sys.exit(1)

    if len(sys.argv) >= 2 and sys.argv[1] in ("--list", "--list-guilds", "--discover"):
        asyncio.run(listar_servidores(token))
        return

    if len(sys.argv) < 2:
        print("Uso: python bot.py <arquivo_de_tarefas.json>")
        print("      python bot.py --list            (lista servidores)")
        sys.exit(1)

    caminho_tarefas = sys.argv[1]
    if not os.path.exists(caminho_tarefas):
        print(f"Arquivo não encontrado: {caminho_tarefas}")
        sys.exit(1)

    dados = carregar_tarefas(caminho_tarefas)
    guild_id = dados.get("guild_id")

    if not guild_id:
        arquivo_servidor = "servidor.txt"
        if os.path.exists(arquivo_servidor):
            with open(arquivo_servidor, "r") as f:
                guild_id = f.read().strip()
            print(f"guild_id lido de {arquivo_servidor}: {guild_id}")
        else:
            print("'guild_id' não informado no JSON e servidor.txt não encontrado.")
            print("Crie servidor.txt com o ID do servidor ou use --list para descobrir.")
            sys.exit(1)

    nome_sessao = dados.get("session", "sessao")
    tarefas = dados.get("tasks", [])
    caminho_resultado = f"operations/execution/{nome_sessao}_resultado.json"

    print(f"Sessão: {nome_sessao}")
    print(f"Servidor ID: {guild_id}")
    print(f"Tarefas: {len(tarefas)}")
    print(f"Resultado: {caminho_resultado}\n")

    asyncio.run(executar_sessao(token, guild_id, tarefas, caminho_resultado))


if __name__ == "__main__":
    main()
